
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
      - ./requirements/nginx/ssl:/etc/ssl/certs
    depends_on:
      - wordpress
    restart: always
    networks:
      - internal

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - wordpress_files:/var/www/html
    restart: always
    env_file:
      - ./.env
    # environment:
    #   WORDPRESS_DB_HOST: mariadb:3306
    #   WORDPRESS_DB_USER: wordpress
    #   WORDPRESS_DB_PASSWORD: wordpresspassword
    #   WORDPRESS_DB_NAME: wordpress
    expose:
      - "80"
    links:
      - mariadb
    networks:
      - internal

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    command: ["sleep", "3600"]
    env_file:
      - ./.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: wordpress
    #   MYSQL_PASSWORD: wordpresspassword
    volumes:
      - wordpress_db:/var/lib/mysql
    restart: always
    networks:
      - internal

volumes:
  wordpress_db:
  wordpress_files:

networks:
  internal:
    driver: bridge