
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception42
    environment:
     - DB_NAME=${DB_NAME}
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
     - DB_HOSTNAME=${DB_HOSTNAME}
     - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
     
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception42
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception42
    environment:
     - SITE_TITLE=${SITE_TITLE}
     - DOMAIN_NAME=${DOMAIN_NAME}
     - WP_ADMIN=${WP_ADMIN}
     - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
     - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
     - WP_USER=${WP_USER}
     - WP_USER_EMAIL=${WP_USER_EMAIL}
     - WP_USER_PASSWORD=${WP_USER_PASSWORD}


volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/msumon/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/msumon/data/mysql
      o: bind

networks:
  inception42:
    driver: bridge