
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - mynetwork
    restart: always

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mynetwork
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
    expose:
      - "9000"

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    command: ["sleep", "3600"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

volumes:
  wordpress_db:
  wordpress_files:

networks:
  mynetwork:
    driver: bridge