FROM ubuntu:latest

# Install necessary packages
RUN apt update && apt install -y \
    zsh \
    git \
    curl \
    wget \
    nano \
    g++ \
    make \
    python3 \
    python3-pip \
    gpg \
    apt-transport-https \
    ca-certificates \
    software-properties-common \
    gnupg2 \
    build-essential \
    && apt-get clean

COPY ubuntu.sh /usr/bin/ubuntu.sh
RUN chmod +x /usr/bin/ubuntu.sh

ENTRYPOINT [ "ubuntu.sh" ]

# COPY webserver 
COPY webserv /home/webserver

ENV USERNAME=sumon
ENV PASSWORD=open
ENV ROOT_PASSWORD=open

WORKDIR /home/webserver

# Keep the container running
CMD ["zsh"]
