version: '3.8'
 
networks:
  backend:

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: img_nginx
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    networks:
      - backend
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    networks:
      - backend
    environment: 
      DATABASE_HOST:       ${DATABASE_HOST}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER:  ${WP_DB_USER}
      WP_DB_PASS:  ${WP_DB_PASS}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USER:     ${WP_ADMIN_USER}
      WP_ADMIN_PASS:     ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USER:           ${WP_USER}
      WP_PASS:           ${WP_PASS}
      WP_EMAIL:         ${WP_EMAIL}
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - backend
    environment:
      DATABASE_ROOT_PASS:   ${DATABASE_ROOT_PASS}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER:  ${WP_DB_USER}
      WP_DB_PASS:  ${WP_DB_PASS}
    restart: always